title: README
date: "2020-05-11"
description: |
  Documentation for setting up ablog. Of course, written using ablog itself.
slug: "readme"
authors:
  - name: Denny Britz
    email: "dennybritz@gmail.com"
    url: https://twitter.com/dennybritz
bibtex: |
  @article{britz2020ablog-readme,
    author={Denny Britz},
    title={ablog README},
    year={2020},
    url={https://ablog-svelte.com/blog/readme},
  }

format: pandoc
pandoc:
  input-files:
    - ../README.md
